In [1]:
import numpy as np

In [9]:
v=np.array([0,1,2,3,4,5,6,7,8,9])
print(v)
print(type(v))
print(v.ndim)
print(np.shape(v))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)


In [15]:
odd=v[1::2]
print(odd)

[1 3 5 7 9]


In [16]:
backward=v[::-1]
print(backward)

[9 8 7 6 5 4 3 2 1 0]


In [17]:
a = np.array([1, 2, 3, 4, 5]) 
b = a[1:4] 
b[0] = 200 
print(a[1])

200


In [74]:
m=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(m)
print('dimension is ',m.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
dimension is  2


In [75]:
reverse=m[:,::-1]
print(reverse)

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [80]:
row=m[::-1]
print(row)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [ ]:
print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [94]:
rev=m[::-1]
print(rev)
print('******************')
rev2=rev[:,::-1]
print(rev2)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]
******************
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [96]:
c=m[::-1,::-1]
print(c)

[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [104]:
q=np.array([[0,0,1,1,1],[0,1,2,3,0],[0,4,5,6,0],[0,7,8,9,0],[0,10,11,12,0],[2,2,2,2,2]])
print(q)

[[ 0  0  1  1  1]
 [ 0  1  2  3  0]
 [ 0  4  5  6  0]
 [ 0  7  8  9  0]
 [ 0 10 11 12  0]
 [ 2  2  2  2  2]]


In [109]:
cut=q[1:-1]
print(cut)
morecut=cut[:,1:-1]
print('*********************')
print(morecut)

[[ 0  1  2  3  0]
 [ 0  4  5  6  0]
 [ 0  7  8  9  0]
 [ 0 10 11 12  0]]
*********************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [111]:
cutting=q[1:-1,1:-1]
print(cutting)
print(cutting.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


# part 2

In [112]:
dt = np.dtype([('country', 'S20'), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])

In [133]:
product = np.dtype([('id', np.int32),('price', 'i4')])
print(product)
print(product['price'])
print(product['id'])

[('id', '<i4'), ('price', '<i4')]
int32
int32


In [143]:
product = np.dtype([('id', np.int32),('price', 'i4')])
data=np.array([(1,100),(2,200),(3,300),(4,400),(5,500),(6,600),(7,700),(8,800)],dtype=product)
print(data[:4])
print(data)

[(1, 100) (2, 200) (3, 300) (4, 400)]
[(1, 100) (2, 200) (3, 300) (4, 400) (5, 500) (6, 600) (7, 700) (8, 800)]


In [144]:
print(data['id'])

[1 2 3 4 5 6 7 8]


In [145]:
print(data['price'])

[100 200 300 400 500 600 700 800]


In [151]:
print(data[0])
print(data['price'][2])

(1, 100)
300


In [154]:
import numpy as np
mytype = [('productID', np.int32), ('price', np.float64)]
stock = np.array([(34765, 603.76), 
                  (45765, 439.93),
                  (99661, 344.19),
                  (12129, 129.39)], dtype=mytype)
print(stock[1])
print(stock["productID"])
print(stock[2]["price"])
print(stock)

(45765, 439.93)
[34765 45765 99661 12129]
344.19
[(34765, 603.76) (45765, 439.93) (99661, 344.19) (12129, 129.39)]
